server:
  port: 8082

spring:
  application:
    name: webclient

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: admin

shop:
  account:
    number: 3

