server:
  port: 8081

spring:
  application:
    name: api-gateway
  profiles:
    active: eclient

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
      import: configserver:http://localhost:8085
