spring:
  cloud:
    openfeign:
      client:
        config:
          payment:
            url: http://localhost:8765/payment
          patternsew:
            url: http://localhost:8765/patterns
          textile:
            url: http://localhost:8765/textile

api:
  basic-uri:
    payment: http://localhost:0/payment/
    patternsew: http://localhost:8765/patterns/
    textile: http://localhost:8765/textile/

shop:
  account:
    number: 3

tmpVar: configServer