spring:
  cloud:
    openfeign:
      client:
        config:
          payment:
            url: http://localhost:8081/payment
          patternsew:
            url: http://localhost:8066/patterns
          textile:
            url: http://localhost:8067/textile

api:
  basic-uri:
    payment: http://localhost:8081/payment/
    patternsew: http://localhost:8066/patterns
    textile: http://localhost:8067/textile

shop:
  account:
    number: 3

tmpVar: configserver