spring:
  cloud:
    openfeign:
      client:
        config:
          payment:
            url: http://localhost:8768/payment
          patternsew:
            url: http://localhost:8768/patterns
          textile:
            url: http://localhost:8768/textile

api:
  basic-uri:
    payment: http://localhost:8768/payment/
    patternsew: http://localhost:8768/patterns/
    textile: http://localhost:8768/textile/

shop:
  account:
    number: 3

tmpVar: configServer