server:
  port: 0

spring:
  application:
    name: payment

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  profiles:
    active: eclient

  discovery:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true

  cloud:
    config:
      import: optional:configserver:http://localhost:8888
      enabled: false

