server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: payment

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  profiles:
    active: eserver

  cloud:
    config:
      import: optional:configserver:http://localhost:8888
      enabled: false


