server:
  port: 8085

spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        bootstrap: true
        composite:
          - type: native
            searchlocations: file://D:/DiplomGB2024/src/main/resources
