server:
  port: 8085

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Evgen986/shop-config.git
          basedir: file://c:/tmp/shop
          default-label: main
