server:
  port: 8085

spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        composite:
          - type: native
            searchLocations: file:D:/DiplomGB2024/src/ain/resources/
